Add provisioning job for dev stage

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -69,7 +69,49 @@ stages:
   displayName: 'Deploy to the dev environment'
   dependsOn: Build
   jobs:
+  - job: Provision
+    displayName: 'Provision azure app service'
+    pool:
+      vmImage: 'ubuntu-18.04'
+    variables:
+    - group: Release
+    steps:
+    - script: |
+      # Exit when a command returns a failure status.
+      set -e
+
+      # Write terraform tfvars
+      echo 'resource_group_location = "'$(ResourceGroupLocation)'"' | tee terraform.tfvars
+
+      # Write backend tfvars
+      echo 'resource_group_name = "tf-storage-rg"' | tee backend.tfvars
+      echo 'storage_account_name = "'$(StorageAccountName)'"' | tee -a backend.tfvars
+      echo 'container_name = "tfstate"' | tee -a backend.tfvars
+      echo 'key = "terraform.tfstate"' | tee -a backend.tfvars
+
+      # Initialize Terraform
+      terraform init -backend-config="backend.tfvars" -input=false
+
+      # Apply terraform plan
+      terraform apply -auto-approve -input=false
+
+      # Get the app service name for the dev environment
+      WebAppNameDev=$(terraform output appservice_name_dev)
+
+      #Write the WebAppNameDev variable to the pipeline
+      echo "##vso[task.setVariable variable=WebAppNameDev;isOutput=true]$WebAppNameDev"
+    name: RunTerraform
+    displayName: Run Terraform
+    env:
+      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
+      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
+      ARM_TENANT_ID: $(ARM_TENANT_ID)
+      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
+
   - deployment: Deploy
+    dependsOn: Provision
+    variables:
+      WebbAppNameDev: $[ dependencies.Provision.outputs['RunTerraform.WebAppNameDev'] ]
     pool:
       vmImage: 'ubuntu-18.04'
     environment: dev
