fixed multiline script identation

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -77,29 +77,29 @@ stages:
     - group: Release
     steps:
     - script: |
-      # Exit when a command returns a failure status.
-      set -e
+        # Exit when a command returns a failure status.
+        set -e
 
-      # Write terraform tfvars
-      echo 'resource_group_location = "'$(ResourceGroupLocation)'"' | tee terraform.tfvars
+        # Write terraform tfvars
+        echo 'resource_group_location = "'$(ResourceGroupLocation)'"' | tee terraform.tfvars
 
-      # Write backend tfvars
-      echo 'resource_group_name = "tf-storage-rg"' | tee backend.tfvars
-      echo 'storage_account_name = "'$(StorageAccountName)'"' | tee -a backend.tfvars
-      echo 'container_name = "tfstate"' | tee -a backend.tfvars
-      echo 'key = "terraform.tfstate"' | tee -a backend.tfvars
+        # Write backend tfvars
+        echo 'resource_group_name = "tf-storage-rg"' | tee backend.tfvars
+        echo 'storage_account_name = "'$(StorageAccountName)'"' | tee -a backend.tfvars
+        echo 'container_name = "tfstate"' | tee -a backend.tfvars
+        echo 'key = "terraform.tfstate"' | tee -a backend.tfvars
 
-      # Initialize Terraform
-      terraform init -backend-config="backend.tfvars" -input=false
+        # Initialize Terraform
+        terraform init -backend-config="backend.tfvars" -input=false
 
-      # Apply terraform plan
-      terraform apply -auto-approve -input=false
+        # Apply terraform plan
+        terraform apply -auto-approve -input=false
 
-      # Get the app service name for the dev environment
-      WebAppNameDev=$(terraform output appservice_name_dev)
+        # Get the app service name for the dev environment
+        WebAppNameDev=$(terraform output appservice_name_dev)
 
-      #Write the WebAppNameDev variable to the pipeline
-      echo "##vso[task.setVariable variable=WebAppNameDev;isOutput=true]$WebAppNameDev"
+        #Write the WebAppNameDev variable to the pipeline
+        echo "##vso[task.setVariable variable=WebAppNameDev;isOutput=true]$WebAppNameDev"
     name: RunTerraform
     displayName: Run Terraform
     env:
